<<<<<<< HEAD
[wokwi]
version = 1
firmware = '.pio\build\esp32doit-devkit-v1\firmware.bin'
=======
[wokwi]
version = 1
firmware = '.pio\build\esp32doit-devkit-v1\firmware.bin'
>>>>>>> master
elf = '.pio\build\esp32doit-devkit-v1\firmware.elf'